name: Trigger auto deployment for johnnyportfolioprojectserver-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/johnnyportfolioprojectserver-app-AutoDeployTrigger-528cb855-098e-4044-9241-6c090232661d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Install Node.js
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.JOHNNYPORTFOLIOPROJECTSERVERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.JOHNNYPORTFOLIOPROJECTSERVERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.JOHNNYPORTFOLIOPROJECTSERVERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: johnnyportfolioprojectserver20250128193741.azurecr.io
          registryUsername: ${{ secrets.JOHNNYPORTFOLIOPROJECTSERVERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.JOHNNYPORTFOLIOPROJECTSERVERAPP_REGISTRY_PASSWORD }}
          containerAppName: johnnyportfolioprojectserver-app
          resourceGroup: NHA
          imageToBuild: johnnyportfolioprojectserver20250128193741.azurecr.io/johnnyportfolioprojectserver-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_

      - name: Install dependencies for Playwright
        run: |
          cd portfolio_ui_test
          npm install

      - name: Run Playwright tests
        run: |
          cd ../../portfolio.ui.test
          npx playwright install # Install Playwright dependencies
          npx playwright test   # Run the tests


