name: Trigger auto deployment for johnnyportfolioprojectserver-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/johnnyportfolioprojectserver-app-AutoDeployTrigger-528cb855-098e-4044-9241-6c090232661d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.JOHNNYPORTFOLIOPROJECTSERVERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.JOHNNYPORTFOLIOPROJECTSERVERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.JOHNNYPORTFOLIOPROJECTSERVERAPP_AZURE_SUBSCRIPTION_ID }}



      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: JohnnyPortfolioProject.Server/Dockerfile
          registryUrl: johnnyportfolioprojectserver20250128193741.azurecr.io
          registryUsername: ${{ secrets.JOHNNYPORTFOLIOPROJECTSERVERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.JOHNNYPORTFOLIOPROJECTSERVERAPP_REGISTRY_PASSWORD }}
          containerAppName: johnnyportfolioprojectserver-app
          resourceGroup: NHA
          imageToBuild: johnnyportfolioprojectserver20250128193741.azurecr.io/johnnyportfolioprojectserver-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_

      # Step to install dependencies for Playwright
      - name: Set up Node.js for Playwright tests
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your Node.js version here

      - name: Install Playwright dependencies
        run: |
          cd portfolio_ui_tests  # Change to your Playwright test directory
          npm install
          npx playwright install

      - name: Run Playwright tests
        run: |
          cd portfolio.ui.tests  # Again, change to the directory containing your tests
          npx playwright test  # This runs the Playwright tests


